baseurl: https://www.adminbraindump.com
languageCode: en-us
theme: stack
title: Admin Brain Dump
enableRobotsTXT: true
googleAnalytics: "UA-239997350-1"

params:
    sidebar:
        compact: false
        emoji: 💩
        subtitle: A mostly organized brain dump
        avatar:
            enabled: true
            local: true
            src: img/brain_logo.png
    widgets:
        homepage:
            - type: search
            - type: tag-cloud
              params:
                    limit: 10
    colorScheme:
        toggle: true
        default: dark

menu: 
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/wdomon
          params:
                icon: github
        - identifier: linkedin
          name: LinkedIn
          url: https://www.linkedin.com/in/wes-domon-0102ab80/
          params:
                icon: linkedin
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              icon: home
              newtab: false
        - identifier: about
          name: About
          url: /about/
          weight: 1
          params:
              icon: user
              newtab: false